### ISSUE TITLE
Babel-node does not execute multiple files

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [bucaran/generator-rise#10]
Babel-node does not execute multiple files [1116](https://github.com/babel/babel/issues/1116). So if you have more than one test, it will only execute the first test. You can use [babel-tape-runner](https://github.com/wavded/babel-tape-runner) and then just run `babel-tape-runner test/*.js | tspec`. However, this does not work with iSparta. iSparta suffers from the same issue, but errors out with babel-tape-runner. 

Will need to spend more time with iSparta and babel-node, unless anyone else has any ideas how to have coverage on more than one file using babel. 

@bucaran if you want me to submit a PR for the Tape fix, let me know.

**Comment by bucaran** [comment]
Well, how would you fix it?

**Comment by TYRONEMICHAEL** [comment]
I can fix this first issue with babel-tape-runner, it is the coverage that is the issue... Ill submit a pull request.

**Comment by bucaran** [comment]
:+1:

**Comment by Hypercubed** [comment]
Just a note that whatever solution you find here needs to be applied to generator-rise itself.  `"test": "babel-node test/*.js | tspec",` does not work, I had to change to "babel-node test/index.js | tspec",`

**Comment by bucaran** [comment]
@Hypercubed True. The "solution" seems to be have a file `index.js` where you can load all your tests like @TYRONEMICHAEL described above.

**Comment by Hypercubed** [comment]
Right, but also having some trouble with isparta.  I change to:

```
    "test": "babel-node test/index.js | tspec",
    "coverage": "babel-node node_modules/isparta/bin/isparta cover --report text test/index.js",
```

**Comment by TYRONEMICHAEL** [comment]
Ya you need to point iSparta to your single index.js file. I can confirm coverage is correct using this method.

**Comment by Hypercubed** [comment]
I also needed to use `node_modules/isparta/bin/isparta` (a js file) rather than `node_modules/.bin/isparta` (a bash file), not sure if it's just me on windows.

**Comment by bucaran** [comment]
Do you have `node_modules/.bin` on your Window's `$PATH` equivalent? @Hypercubed

**Comment by Hypercubed** [comment]
I don't think I need to... it's a relative path and the file is found.  Honestly I don't undertand what the line  `babel-node node_modules/.bin/isparta cover --report text test/*.js is tring to do.  `node_modules/.bin/isparta` is a bash file how does it ever work to open a bash file with node (or babel-node)?  Is `node_modules/.bin/isparta` a js file on *nix?  If instead I point to the js file `node_modules/isparta/bin/isparta` it works.  I've never seen this done before... could me some evn difference.

**Comment by Hypercubed** [comment]
https://github.com/npm/npm/issues/3883#issuecomment-31859121

**Comment by bucaran** [comment]
Right. You don't need to in this case. I do, because I don't install packages globally. But that has nothing to do with this issue. My bad for bringing that up.

So, `.bin/isparta` is a soft link to `../isparta/bin/isparta` which is the node script, but it's useless and it should point to what you have.

Can you send me a PR with this bit too?

**Comment by TYRONEMICHAEL** [comment]
Howcome npm resolves `babel-node`, but wont resolve `babel-node isparta...`? Why do you have to explicitly point to the .bin folder if it is in the second argument?

**Comment by Hypercubed** [comment]
npm run adds node_modules/.bin to the PATH (https://docs.npmjs.com/cli/run-script).  Executable is `babel-node` so that gets resolved.  Then if the first argument to `babel-node` is `isparta` it looks for isparta.js in the cwd.  The path is never resolved for arguments.
