### ISSUE TITLE
compose with generator-travis

### ISSUE THREAD

**Issue by iamstarkov** [bucaran/generator-rise#13]
It is the easiest way to stop worrying about travis config. https://github.com/iamstarkov/generator-travis
what do you think? if its okay for you, i will create pull-request

**Comment by bucaran** [comment]
Go for it!

**Comment by Hypercubed** [comment]
Could you do this same with https://github.com/jozefizso/generator-license?

**Comment by iamstarkov** [comment]
@Hypercubed  what do you mean? integrate generator-license in generator-rise or integrate generator-travis into generator-license?

**Comment by Hypercubed** [comment]
I meant could someone (not necessarillay you) integrate generator-license into generator-rise.

**Comment by bucaran** [comment]
Maybe @jozefizso himself could give us a hand? :pray:

**Comment by iamstarkov** [comment]
generator-Travis merged so issue can be closed
