### ISSUE TITLE
too agressive on npm

### ISSUE THREAD

**Issue by iamstarkov** [bucaran/generator-rise#18]
rise wants to punch me inda face right after I opened a npm page about it

![screen shot 2015-11-20 at 10 32 32](https://cloud.githubusercontent.com/assets/559321/11296386/18d690ce-8f72-11e5-853e-cd8d560bb170.png)

**Comment by bucaran** [comment]
Ah, that's because we are using percentages in the README instead of fixed width and height. Changing the width or height to 100px or something should do.

**Comment by bucaran** [comment]
ba86f070f5d2e5f2fc7577e4c4ebce7d256c2011

**Comment by iamstarkov** [comment]
it doznt halp! https://www.npmjs.com/package/generator-rise

**Comment by bucaran** [comment]
Do you have any idea why?

**Comment by iamstarkov** [comment]
nah, i dont even know, how to fix it, postcss also has the [same](https://github.com/postcss/postcss#readme) [issue](https://www.npmjs.com/package/postcss)

**Comment by marvinroger** [comment]
This is because when npm renders the README, it strips more markup than GitHub does. So the size markup is deleted, like the markup needed to center. The only solution is to manually resize the image.
