### ISSUE TITLE
Freeze dependencies in package.json

### ISSUE THREAD

**Issue by marvinroger** [bucaran/generator-rise#23]
I feel bad using this package, as the `package.json` sometimes uses `*` for dependencies. This is bad, as it can cause issues [like the one with Babel 6 on fly](https://github.com/bucaran/fly/issues/115#issuecomment-159949214).

The best option is to mark dependency version with a `^`, therefore using latest non-breaking version. Plus, dependencies are tracked with david-dm, so this is easy to update when there is a newer breaking dependency version.

**Comment by bucaran** [comment]
Sounds reasonable. Would you like to send a patch?

**Comment by marvinroger** [comment]
Yes, I will.
