### ISSUE TITLE
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly

### ISSUE THREAD

**Issue by SokichiFujita** [bucaran/generator-rise#28]
`yo rise` command displays the warning and doesn't generate anything.

**Comment by bucaran** [comment]
Do you think this is an easy fix?

**Comment by iamstarkov** [comment]
it is, if the problem only in deprecation

**Comment by SokichiFujita** [comment]
I'm not sure now. But, maybe it is easy.

**Comment by ratracegrad** [comment]
Because of this warning, this generator will not generate anything. Are there plans to fix this warning or have the owners abandoned?

**Comment by bucaran** [comment]
Hi @ratracegrad. Does this fix the problem?

**Comment by ratracegrad** [comment]
Hello @bucaran ,

Ran npm update on the generator and it picked up the change and built successfully.

**Comment by bucaran** [comment]
Thanks @ratracegrad!
