### ISSUE TITLE
Babel for tests

### ISSUE THREAD

**Issue by knownasilya** [bucaran/generator-rise#6]
Would love to see babel used for tests, especially for projects that deal with decorators or other features that would require babel for the tests.

**Comment by iamstarkov** [comment]
actually, tests in generated modules are already running through babel https://github.com/bucaran/generator-rise/blob/master/app/templates/package.json#L15

**Comment by knownasilya** [comment]
Sweet, didn't notice. Great generator!

**Comment by iamstarkov** [comment]
=) you also can take a look at another [tiny es generator](https://github.com/iamstarkov/generator-tiny-es-nm/)
